version: "3.9"
services:
  db:
    image: postgres:alpine
    environment: 
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: task-manager
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
